version: '3.8'

services:
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - backend

  mysql-product:
    image: mysql:8
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql
    networks:
      - backend

  mysql-order:
    image: mysql:8
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql
    networks:
      - backend

  user-service:
    image: user-service:1.0
    container_name: user-service
    depends_on:
      - mysql-user
    expose:
      - "8081"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8081
      - DB_HOST=mysql-user
      - DB_PORT=3306
      - DB_NAME=user_service_db
      - DB_USER=root
      - DB_PASSWORD=root
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - backend

  product-service:
    image: product-service:1.0
    container_name: product-service
    depends_on:
      - mysql-product
    expose:
      - "8082"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8082
      - DB_HOST=mysql-product
      - DB_PORT=3306
      - DB_NAME=product_service_db
      - DB_USER=root
      - DB_PASSWORD=root
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - backend

  order-service:
    image: order-service:1.0
    container_name: order-service
    depends_on:
      - mysql-order
    expose:
      - "8083"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_PROFILES_ACTIVE=prod # Chọn profile dev
      - PORT=8083
      - DB_HOST=mysql-order
      - DB_PORT=3306
      - DB_NAME=order_service_db
      - DB_USER=root
      - DB_PASSWORD=root
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=8082
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - PAYMENT_RESULT_URL=${PAYMENT_RESULT_URL}
    networks:
      - backend

  api-gateway:
    image: api-gateway:1.3
    container_name: api-gateway
    depends_on: # Chờ các service khác khởi động
      - user-service
      - product-service
      - order-service
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080
#      - FRONT_END_HOST=frontend
#      - FRONT_END_PORT=3000
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=8081
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=8082
      - ORDER_SERVICE_HOST=order-service
      - ORDER_SERVICE_PORT=8083
    networks:
      - backend
  frontend:
    image: buyzy_frontend:2.4
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - backend



volumes:
  mysql-user-data:
  mysql-product-data:
  mysql-order-data:

networks:
  backend:
    driver: bridge # Tạo mạng riêng cho các service