apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # api-gateway
  FRONTEND_SERVICE_HOST: "192.168.49.2"
  FRONTEND_SERVICE_PORT: "30000"
  USER_SERVICE_HOST: "user-service"
  USER_SERVICE_PORT: "8081"
  PRODUCT_SERVICE_HOST: "product-service"
  PRODUCT_SERVICE_PORT: "8082"
  ORDER_SERVICE_HOST: "order-service"
  ORDER_SERVICE_PORT: "8083"

  # user-service

  VNPAY_URL: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  VNPAY_TMN_CODE: "OW8Y2T76"
  VNPAY_RETURN_URL: "http://192.168.49.2:30001/api/v1/payment/vn-pay-return"
  PAYMENT_RESULT_URL: "http://192.168.49.2:30000/payment-result"