package com.ecommerce.order_service.entity;

import com.ecommerce.order_service.enums.PaymentMethod;
import com.ecommerce.order_service.enums.PaymentStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
@Table(name = "payments")
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    private Double amount;

    private Long userId;

    @OneToOne
    @JoinColumn(name = "order_id")
    @JsonIgnore
    private Order order;

    @Column(name = "transaction_id", unique = true)
    private String transactionId;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private PaymentStatus status; // This can be an enum as well, depending on your design

    // Constructors, getters, and setters can be generated by Lombok
}
