package com.ecommerce.order_service.entity;

import com.ecommerce.order_service.enums.PaymentMethod;
import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
@Table(name = "payments")
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    private Double amount;

    private Long userId;

    @OneToOne
    @JoinColumn(name = "order_id")
    private Order order;

    // Constructors, getters, and setters can be generated by Lombok
}
