apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: thinhnguet/product-service:final
#        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: PORT
            value: "8082"
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: DB_HOST
            value: mysql-product
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: product_service_db

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD

          - name: CLOUDINARY_CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: CLOUDINARY_CLOUD_NAME

          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: CLOUDINARY_API_KEY

          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
    selector:
        app: product-service
    ports:
        - port: 8082
          targetPort: 8082
          nodePort: 30002
    type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi
    storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  labels:
    app: mysql-product
spec:
    replicas: 1
    selector:
        matchLabels:
          app: mysql-product
    template:
        metadata:
          labels:
            app: mysql-product
        spec:
          containers:
          - name: mysql-product
            image: mysql
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 3306
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: product_service_db
            volumeMounts:
              - name: mysql-product-storage
                mountPath: /var/lib/mysql
          volumes:
            - name: mysql-product-storage
              persistentVolumeClaim:
                claimName: mysql-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product
spec:
    selector:
        app: mysql-product
    ports:
        - port: 3306
          targetPort: 3306
    type: ClusterIP