apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: thinhnguet/user-service:latest
#          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: PORT
              value: "8081"
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: DB_HOST
              value: mysql-user
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: user_service_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD

            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GMAIL_USERNAME

            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GMAIL_PASSWORD

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service

metadata:
  name: user-service
  labels:
    app: user-service
spec:
    selector:
        app: user-service
    ports:
      - name: http
        port: 8081
        targetPort: 8081
    type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user
  labels:
    app: mysql-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
      - name: mysql-user
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: user_service_db
        volumeMounts:
        - name: mysql-user-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-user-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-user-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-user
spec:
    selector:
        app: mysql-user
    ports:
        - port: 3306
          targetPort: 3306
    type: ClusterIP